### ISSUE TITLE
Compatibility issues with WooCommerce 4.5

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#794]
#### 🔨  Styling issues

1. Disabled style of Toggle component is disappeared
    ![2021-06-17 10 42 30](https://user-images.githubusercontent.com/17420811/122323052-0d78ed80-cf59-11eb-8aa6-7f1be167fcf4.png)
2. Disabled style of primary Button components are disappeared
    ![2021-06-17 10 47 22](https://user-images.githubusercontent.com/17420811/122323553-da832980-cf59-11eb-95e6-a6eb879b8b81.png)
3. Full-container layout is broken
    ![2021-06-17 11 09 48](https://user-images.githubusercontent.com/17420811/122325511-4fa42e00-cf5d-11eb-83cb-14b78a788b7e.png)
4. Full-screen layout has a gap space on the top of page
    ![2021-06-17 11 15 51](https://user-images.githubusercontent.com/17420811/122325636-88dc9e00-cf5d-11eb-969c-cede179c8cc9.png)
5. The header layout of Product Feed table is broken
    ![2021-06-17 12 23 18](https://user-images.githubusercontent.com/17420811/122331995-4f5d6000-cf68-11eb-9daf-75c3aa415b7b.png)

#### 🔨  Code issues

1.  The [useStoreCountry hook](https://github.com/woocommerce/google-listings-and-ads/blob/d6290882f5c7e9038d11138606d50f5312a77d63/js/src/hooks/useStoreCountry.js#L16-L17) is broken because the 'general' group is unavailable in the `wcSettings`
    ![image](https://user-images.githubusercontent.com/17420811/122330121-2be4e600-cf65-11eb-81f7-0f3defd98192.png)

### Expected behavior:

Styling issues

- [ ] Display disabled style of Toggle component
- [ ] Display disabled style of primary Button component
- [ ] Fix full-container layout
- [ ] No gap at the top of the full-screen layout
- [ ] Fix the header layout of Product Feed table

Code issues

- [ ] The `useStoreCountry` hook should return store country code correctly

### Steps to reproduce:

1. Deactivate *WooCommerce Admin*
2. Install *WooCommerce* 4.5.0

### Additional details:

Disabled primary button issue https://github.com/woocommerce/woocommerce-admin/issues/5912 was fixed but the issue still existing in older WC versions.

**Comment by findingsimple** [comment]
Nice finds @eason9487 - we'll probably end up bumping the minimum WC version support. When we started GLA WooCommerce 4.5 was [L-2](https://developer.woocommerce.com/what-we-support/). Now that we've released 4.5 is getting fairly old.

**Comment by eason9487** [comment]
@jconroy, do we have the next minimum version that we expect to support? Some issues still occur in newer WC versions, such as version 4.9. I can modify this ticket based on the next minimum version.

**Comment by eason9487** [comment]
Looks like we can bump the minimum WC version support to 5.2.0.

**Comment by eason9487** [comment]
Close issue: these compatibility issues would not appear in WooCommerce 5.2.0.
